// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/tools/patrol-overview.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@1.0.0";
import { ToolError } from "npm:@lovable.dev/mcp-js@1.0.0";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js";
function env(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configured(names) {
  return names.map((name) => env(name)?.trim()).find(Boolean);
}
function url() {
  const value = configured(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!value) throw new Error("Backend URL is not configured");
  return value;
}
function key() {
  const direct = configured(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY", "SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (direct) return direct;
  const raw = env("SUPABASE_PUBLISHABLE_KEYS");
  if (raw) {
    try {
      const values = Object.values(JSON.parse(raw));
      const found = values.find((value) => typeof value === "string" && value.trim().length > 10);
      if (found) return found;
    } catch {
    }
  }
  throw new Error("Backend publishable key is not configured");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("A signed-in agent connection is required.");
  return createClient(url(), key(), { global: { headers: { Authorization: `Bearer ${token}` } }, auth: { persistSession: false, autoRefreshToken: false } });
}

// src/lib/mcp/tools/patrol-overview.ts
var patrol_overview_default = defineTool({
  name: "patrol_overview",
  title: "Patrol overview",
  description: "Read the latest guard locations, statuses, incidents, and checkpoint activity visible to the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Sign in to SecurePatrol before using patrol monitoring.");
    const client = supabaseForUser(ctx);
    const [profiles, gps, incidents, logs, checkpoints] = await Promise.all([
      client.from("profiles").select("user_id,name,role,status,last_seen"),
      client.from("gps_tracking").select("guard_id,guard_name,lat,lng,status,is_moving,timestamp").order("timestamp", { ascending: false }).limit(100),
      client.from("incidents").select("id,guard_name,type,description,lat,lng,resolved,timestamp").order("timestamp", { ascending: false }).limit(50),
      client.from("patrol_logs").select("id,guard_name,checkpoint_name,timestamp,lat,lng").order("timestamp", { ascending: false }).limit(100),
      client.from("checkpoints").select("id,name,location,lat,lng,last_scanned,last_scanned_by")
    ]);
    const firstError = [profiles, gps, incidents, logs, checkpoints].find((result) => result.error)?.error;
    if (firstError) throw new ToolError(firstError.message);
    return { content: [{ type: "text", text: JSON.stringify({ profiles: profiles.data ?? [], latestLocations: gps.data ?? [], incidents: incidents.data ?? [], patrolLogs: logs.data ?? [], checkpoints: checkpoints.data ?? [] }) }] };
  }
});

// src/lib/mcp/tools/active-alerts.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@1.0.0";
var active_alerts_default = defineTool2({
  name: "active_alerts",
  title: "Active alerts",
  description: "List unresolved SecurePatrol alerts for the signed-in user.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Sign in to SecurePatrol before using alert monitoring.");
    const { data, error } = await supabaseForUser(ctx).from("alerts").select("id,message,severity,type,timestamp,dismissed").eq("dismissed", false).order("timestamp", { ascending: false }).limit(50);
    if (error) throw new ToolError2(error.message);
    return { content: [{ type: "text", text: JSON.stringify(data ?? []) }] };
  }
});

// src/lib/mcp/index.ts
var projectRef = "qngdpmztkxsbvczkldyt";
var mcp_default = defineMcp({
  name: "securepatrol",
  title: "SecurePatrol",
  version: "1.0.0",
  instructions: "Authenticated monitoring tools for SecurePatrol guard patrols, live telemetry, checkpoints, incidents, and alerts.",
  auth: auth.oauth.issuer({ issuer: `https://${projectRef}.supabase.co/auth/v1`, acceptedAudiences: "authenticated" }),
  tools: [patrol_overview_default, active_alerts_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@1.0.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
